export const ElectricMeter = [
   {
      "name":"A1-01",
      "area":"A",
      "owner":"Nguyễn Thị Kim Nga",
      "oldElectricIndex":24369,
      "price":4253,
   },
   {
      "name":"A1-02",
      "area":"A",
      "owner":"Nguyễn Thị Kim Nga",
      "oldElectricIndex":24369,
      "price":4253,
   },
   {
      "name":"A1-03",
      "area":"A",
      "owner":"Nguyễn Thị Kim Nga",
      "oldElectricIndex":24369,
      "price":4253,
   },
   {
      "name":"A1-01",
      "area":"A",
      "owner":"Nguyễn Thị Kim Nga",
      "oldElectricIndex":24369,
      "price":4253,
   },
   {
      "name":"A2-01",
      "area":"A",
      "owner":"Nguyễn Thị Kim Nga",
      "oldElectricIndex":24369,
      "price":4253,
   },
   {
      "name":"A3-01",
      "area":"A",
      "owner":"Nguyễn Thị Kim Nga",
      "oldElectricIndex":24369,
      "price":4253,
   },
   {
      "name":"A1-01",
      "area":"A",
      "owner":"Nguyễn Thị Kim Nga",
      "oldElectricIndex":24369,
      "price":4253,
   },
   {
      "name":"A1-02",
      "area":"A",
      "owner":"Nguyễn Thị Kim Nga",
      "oldElectricIndex":24369,
      "price":4253,
   },
   {
      "name":"A1-03",
      "area":"A",
      "owner":"Nguyễn Thị Kim Nga",
      "oldElectricIndex":24369,
      "price":4253,
   },
   {
      "name":"A1-01",
      "area":"B",
      "owner":"Nguyễn Thị Kim Nga",
      "oldElectricIndex":24369,
      "price":4253,
   },
   {
      "name":"2-01",
      "area":"B",
      "owner":"Nguyễn Thị Kim Nga",
      "oldElectricIndex":24369,
      "price":4253,
   },
   {
      "name":"A3-01",
      "area":"A",
      "owner":"Nguyễn Thị Kim Nga",
      "oldElectricIndex":24369,
      "price":4253,
   },
   {
      "name":"F1-01",
      "area":"B",
      "owner":"Nguyễn Thị Kim Nga",
      "oldElectricIndex":24369,
      "price":4253,
   },
   {
      "name":"F1-02",
      "area":"B",
      "owner":"Nguyễn Thị Kim Nga",
      "oldElectricIndex":24369,
      "price":4253,
   },
   {
      "name":"F1-03",
      "area":"B",
      "owner":"Nguyễn Thị Kim Nga",
      "oldElectricIndex":24369,
      "price":4253,
   },
   {
      "name":"H1-01",
      "area":"B",
      "owner":"Nguyễn Thị Kim Nga",
      "oldElectricIndex":24369,
      "price":4253,
   },
   {
      "name":"H2-01",
      "area":"B",
      "owner":"Nguyễn Thị Kim Nga",
      "oldElectricIndex":24369,
      "price":4253,
   },
   {
      "name":"H3-01",
      "area":"B",
      "owner":"Nguyễn Thị Kim Nga",
      "oldElectricIndex":24369,
      "price":4253,
   },
   {
      "name":"I1-01",
      "area":"B",
      "owner":"Nguyễn Thị Kim Nga",
      "oldElectricIndex":24369,
      "price":4253,
   },
   {
      "name":"I1-02",
      "area":"B",
      "owner":"Nguyễn Thị Kim Nga",
      "oldElectricIndex":24369,
      "price":4253,
   },
   {
      "name":"I1-03",
      "area":"B",
      "owner":"Nguyễn Thị Kim Nga",
      "oldElectricIndex":24369,
      "price":4253,
   },
]
export const  WaterMeter = [
   {
      "name":"A08-C",
      "area":"C",
      "owner":"Nguyễn Thị Kim Nga",
      "oldElectricIndex":24369,
      "price":30800,
   },
   {
      "name":"1C",
      "area":"C",
      "owner":"Nguyễn Thị Kim Nga",
      "oldElectricIndex":24369,
      "price":30800,
   },
   {
      "name":"2C",
      "area":"C",
      "owner":"Nguyễn Thị Kim Nga",
      "oldElectricIndex":24369,
      "price":30800,
   },
   {
      "name":"3C",
      "area":"C",
      "owner":"Nguyễn Thị Kim Nga",
      "oldElectricIndex":24369,
      "price":30800,
   },
   {
      "name":"4C",
      "area":"C",
      "owner":"Nguyễn Thị Kim Nga",
      "oldElectricIndex":24369,
      "price":30800,
   },
   {
      "name":"5C",
      "area":"C",
      "owner":"Nguyễn Thị Kim Nga",
      "oldElectricIndex":24369,
      "price":30800,
   },
   {
      "name":"6C",
      "area":"C",
      "owner":"Nguyễn Thị Kim Nga",
      "oldElectricIndex":24369,
      "price":30800,
   },
   {
      "name":"7C",
      "area":"C",
      "owner":"Nguyễn Thị Kim Nga",
      "oldElectricIndex":24369,
      "price":30800,
   },
   {
      "name":"8C",
      "area":"C",
      "owner":"Nguyễn Thị Kim Nga",
      "oldElectricIndex":24369,
      "price":30800,
   },
   {
      "name":"A02-C",
      "area":"C",
      "owner":"Nguyễn Thị Kim Nga",
      "oldElectricIndex":24369,
      "price":30800,
   },
   {
      "name":"A03-C",
      "area":"C",
      "owner":"Nguyễn Thị Kim Nga",
      "oldElectricIndex":24369,
      "price":30800
   },
   {
      "name":"K01",
      "area":"K",
      "owner":"Nguyễn Thị Kim Nga",
      "oldElectricIndex":24369,
      "price":30800
   },
   {
      "name":"K02",
      "area":"K",
      "owner":"Nguyễn Thị Kim Nga",
      "oldElectricIndex":24369,
      "price":30800
   },
   {
      "name":"K03",
      "area":"K",
      "owner":"Nguyễn Thị Kim Nga",
      "oldElectricIndex":24369,
      "price":30800
   },
   {
      "name":"K04",
      "area":"K",
      "owner":"Nguyễn Thị Kim Nga",
      "oldElectricIndex":24369,
      "price":30800
   },
   {
      "name":"K05",
      "area":"K",
      "owner":"Nguyễn Thị Kim Nga",
      "oldElectricIndex":24369,
      "price":30800
   },
   {
      "name":"K06",
      "area":"K",
      "owner":"Nguyễn Thị Kim Nga",
      "oldElectricIndex":24369,
      "price":30800
   },
   {
      "name":"K07",
      "area":"K",
      "owner":"Nguyễn Thị Kim Nga",
      "oldElectricIndex":24369,
      "price":30800
   },
   {
      "name":"K08",
      "area":"K",
      "owner":"Nguyễn Thị Kim Nga",
      "oldElectricIndex":24369,
      "price":30800
   },

]
